# place project specific paths in variables to make the rest of the script more generic
variables:  
  NUGET_PATH: 'D:\Program\bin\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe'

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - echo "Nuget Restoring..."
    - '"%NUGET_PATH%" restore'
    - echo "MSBuild..."
    - '"%MSBUILD_PATH%" /p:Configuration=Release /v:quiet /clp:ErrorsOnly /nologo' # build the project
  artifacts:
    name: "%CI_PROJECT_NAME%-%CI_BUILD_ID%"
    paths:
      - 'output/**\*.nupkg'

deploy_job:
  stage: deploy
  only:
    - /(release)|(dev)/
  script:
    - 'build/build.bat'

  dependencies:
    - build_job