version: 1.0.0.{build}
branches:
  only:
    - master
    - release
    - dev
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_folder: c:\projects\GodSharp.Logging
install:
- cmd: nuget restore
build:
  project: GodSharp.Logging.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: output/**\*.nupkg
test: off
deploy:
- provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: s388/c8yQWnGyZ9v9cUDfBe4ud6MFl/ouUEEBruiN5j5+LjSQ4giGKMKuLuvglS1
  artifact: output/**\*.nupkg
  on:
    branch: /(release)|(dev)/
- provider: NuGet
  server: https://www.myget.org/F/godsharp/api/v2/package
  api_key:
    secure: CKm5m2qGYNYnh5yDUE2zKfN+JKBmO5xmtG80AP0yni9yPBqDOaRQ48Y/4k8KGo2y
  artifact: output/**\*.nupkg
  on:
    branch: /(release)|(dev)/
- provider: GitHub
  auth_token:
    secure: uCHTzET52dtiexqTKhgQmup+EBGZs1Afw6eBMfvN4PbQ720YaybNd890Y96ISZ0T
  artifact: output/**\*.nupkg
  draft: true
  force_update: true
  on:
    branch: /(release)|(dev)/